version: '3'
services:
  podweenify:
    image: devyassinepro/podweenify:latest
    ports:
      - "8080:80"
    restart: always

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"